branch-defaults:
  deploying_to_aws:
    environment: hobnob-aws
  master:
    environment: navrajsTest-env
global:
  application_name: navraj's test
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
